version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=TachDb
    ports:
      - '5432:5432'

  event:
    container_name: tache_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8070:8070'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/TachDb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
    networks:
      - zouhayr-network
